### ISSUE TITLE
Typo in iptables.service

### ISSUE THREAD

**Issue by Phyks** [srdja/debian-systemd-iptables#1]
Hi,

It seems there is a slight error in the `iptables.service` file, [here](https://github.com/srdja/debian-systemd-iptables/blob/master/systemd-iptables1.0-0/usr/lib/systemd/system/iptables.service#L8).

I guess one should read

```
ExecStop=/usr/lib/systemd/scripts/iptables-flush
```

without the trailing `6`, which is for `ip6tables`.

Thanks for the work on this package!

**Comment by srdja** [comment]
Hey @Phyks, thanks for spotting this error! I've made the fix and pushed a new [release](https://github.com/srdja/debian-systemd-iptables/releases/tag/1.1.0).

**Comment by Phyks** [comment]
Awesome, thanks!
